name: Create Armbian OS List

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Build everyday
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build OS List File
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate OS List
        run: python main.py > os_list.json

      - name: Pre-Release
        uses: softprops/action-gh-release@v2
        if: github.event_name != 'pull_request'
        with:
          prerelease: true
          name: Continuous Release
          tag_name: continuous-release
          files: os_list.json
